### ISSUE TITLE
Can't clone this repo onto laptop

### ISSUE THREAD

**Issue by pulkitsinghal** [eklipse2k8/FilterKit#2]
Initially the clone message results in:

``````
Submodule 'lib/GPUImage' (git@github.com:eklipse2k8/GPUImage.git) registered for path 'lib/GPUImage'
Cloning into 'lib/GPUImage'...
Permission denied (publickey).
fatal: The remote end hung up unexpectedly```
``````

Afterwards if I change the .gitmodules and .git/config files so that they use a read-only url for this submodule, it still fails and this time with:

```
Submodule 'lib/GPUImage' () registered for path 'lib/GPUImage'
fatal: Needed a single revision
Unable to find current revision in submodule path 'lib/GPUImage'
```

**Comment by eklipse2k8** [comment]
Can you try again? That's weird. GPUImage has the same permission as FilterKit.  You can always clone it and set it to your local repo too.

What version of git do you have installed?

**Comment by pulkitsinghal** [comment]
```
git -c diff.mnemonicprefix=false -c core.quotepath=false clone --recursive https://github.com/eklipse2k8/FilterKit /Users/pulkitsinghal/dev/FilterKit 
Permission denied (publickey).
fatal: The remote end hung up unexpectedly
Clone of 'git@github.com:eklipse2k8/GPUImage.git' into submodule path 'lib/GPUImage' failed
Cloning into '/Users/pulkitsinghal/dev/FilterKit'...
Submodule 'lib/GPUImage' (git@github.com:eklipse2k8/GPUImage.git) registered for path 'lib/GPUImage'
Cloning into 'lib/GPUImage'...
fatal: destination path '/Users/pulkitsinghal/dev/FilterKit' already exists and is not an empty directory.
Completed with errors, see above
```

**Comment by AliSoftware** [comment]
This is usually a problem with some firewalls that don't accept `git://` URLs or some other strange filtering rules of your proxy. I had this issue recently with one of my GIT repository that didn't want to clone submodules on my Mac at work while it had no problem cloning it at home (see [here](https://github.com/AliSoftware/OHHTTPStubs/commit/a6580124f1bce23733d2ae8b4c6bacb5f92da0d6))

@pulkitsinghal : Try grepping `GPUImage.git` in your local working copy and replace its `git://` URL with `http://` (which is equivalent but will probably be better accepted by your firewall or proxy or whatever filters out the request on your network configuration).
You will probably find this `git://` URL of course in the `.gitmodule` file, but also in your local `.git/config` file and in `.git/modules/lib/GPUImage/config` files. Once your changed the URL scheme, remove the empty GPUImage folder that was created by your previously failed `git clone`, and use `git submodule update` to fetch it again but using the modified URL.

@eklipse2k8 : you could consider changing the URL to `http://` in your `.gitmodule` file directly so that other people that will clone your project in the future won't have the problem and won't need to modify their local `config` files to fix it after their initial `clone`.

HTH
